'use strict';

module.exports = {
  DEMO_CAPITAL: 10000,
  BASE_SHARES: 500,
  LOOP_MS: 500,
  CCXT_EXCHANGE: process.env.CCXT_EXCHANGE || 'coinbase',
  CCXT_SYMBOL: process.env.CCXT_SYMBOL || '',
  CCXT_POLL_MS: 500,
  CCXT_STALE_MS: 2000,
  SIGNAL_LOOKBACK_MS: 1000,
  SIGNAL_LOOKBACK_TOLERANCE_MS: 250,
  BTC_MOVE_THRESHOLD_USD: 10,
  PRICE_FEED_FALLBACK_MS: 1000,
  PRICE_STALE_MS: 2500,
  SETTLEMENT_POLL_MS: 1000,
  RESOLUTION_RETRY_MS: 5000,
  CRYPTO_TAKER_FEE_RATE: 0.07,
  CRYPTO_MAKER_REBATE_POOL_SHARE: 0.20,
};
