'use strict';
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const { MomentumLagEngine } = require('./engine');

const app = express();
const server = http.createServer(app);
const io = new Server(server, { pingInterval: 2000, pingTimeout: 5000 });
const port = process.env.PORT || 8080;
const engine = new MomentumLagEngine({
  onTick: markets => io.emit('tick', { t: Date.now(), markets }),
  onLog: line => {
    console.log(line);
    io.emit('log', line);
  },
});

app.get('/healthz', (_, response) => response.sendStatus(200));
app.get('/api/status', (_, response) => {
  try { response.json(engine.buildState()); }
  catch (error) { response.status(500).json({ error: error.message }); }
});

const dashboard = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BTC Divergence Bot</title>
<style>
:root{--bg:#03060a;--panel:#080d15;--card:#050a11;--line:#182432;--muted:#7d8d9f;--blue:#25d3f0;--green:#15ff9c;--red:#ff4a68;--gold:#ffd166;--purple:#a78bfa}
*{box-sizing:border-box;margin:0;padding:0}html{-webkit-text-size-adjust:100%}
body{background:var(--bg);color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;font-weight:700;padding-bottom:24px}
.shell{width:min(1500px,100%);margin:auto;padding:12px}.topbar{padding:12px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(135deg,#081323,#03060a);display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}
.brand{display:flex;gap:10px;align-items:center}.brand-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#0e1a29;color:var(--blue);border:1px solid #20364b}h1{font-size:18px}.sub{font-size:9px;color:var(--muted);margin-top:2px}
.pills{display:flex;gap:6px;flex-wrap:wrap}.pill{font-size:9px;text-transform:uppercase;padding:5px 8px;border-radius:999px;background:#111a26;border:1px solid var(--line)}.live{color:var(--green);background:#051b17;border-color:#12483a}.warn{color:var(--gold)}
.kpis{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:7px;margin-top:10px}.metric{min-width:0;padding:10px;background:var(--panel);border:1px solid var(--line);border-radius:13px}.label{font-size:8px;color:var(--muted);text-transform:uppercase;letter-spacing:.7px}.value{font-size:16px;margin-top:3px;overflow-wrap:anywhere}.small{font-size:8px;color:var(--muted);margin-top:2px}
.panel{padding:11px;background:var(--panel);border:1px solid var(--line);border-radius:15px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:1px}.panel-head strong{color:#fff;font-size:12px;text-transform:none}
.two-col{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(0,1fr);gap:8px;margin-top:8px}.chart{height:170px;margin-top:8px}.chart svg{width:100%;height:100%}
.config-grid,.records-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:8px}.config-item,.record{min-width:0;padding:7px;background:var(--card);border:1px solid #14202d;border-radius:8px;font-size:9px;color:var(--muted)}.config-item b,.record-value{display:block;color:#fff;font-size:11px;margin-top:2px;overflow-wrap:anywhere}.record-value{font-size:17px}
.markets,.windows,.positions,.results,.feed{display:grid;gap:6px;margin-top:8px}.markets{grid-template-columns:repeat(2,minmax(0,1fr))}
.market-card{padding:9px;background:var(--card);border:1px solid var(--line);border-radius:12px;min-width:0}.market-top{display:flex;justify-content:space-between;gap:6px}.asset-name{font-size:17px;color:var(--gold)}.timer{color:var(--blue);text-align:right;font-size:14px}.timer span{display:block;font-size:8px;color:var(--muted)}
.sides{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px}.side{padding:8px;border-radius:9px;border:1px solid #172433;background:#081119;text-align:center}.side-label{font-size:8px;text-transform:uppercase;letter-spacing:.8px}.up-label{color:var(--blue)}.down-label{color:var(--purple)}.mid{font-size:28px;margin-top:2px;line-height:1}.quote-row{display:flex;justify-content:center;gap:8px;font-size:10px;margin-top:3px}.quote{color:var(--muted)}.quote b{color:#fff}.delta{font-size:8px;margin-top:2px;height:11px}
.signal-line{margin-top:7px;padding-top:6px;border-top:1px solid #131f2c;display:flex;justify-content:space-between;gap:5px;font-size:8px;color:var(--muted);flex-wrap:wrap}.signal-buy{color:var(--green)!important}.signal-lead{color:var(--blue)!important}.signal-final{color:var(--gold)!important}
.position{padding:9px;background:var(--card);border:1px solid var(--line);border-radius:10px}.pos-top{display:flex;justify-content:space-between;gap:6px}.pos-shares{font-size:19px;color:var(--blue);margin-top:2px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin-top:7px}.cell{text-align:center;padding:5px;background:#070d14;border-radius:6px;border:1px solid #16202c;font-size:8px;color:var(--muted)}.cell b{display:block;color:#fff;font-size:10px;margin-top:2px}
.window-card{padding:9px;background:var(--card);border:1px solid var(--line);border-radius:10px}.window-shares{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:7px;text-align:center}.share-box{padding:7px;background:#081119;border:1px solid #172433;border-radius:8px}.share-value{font-size:20px;margin-top:2px}
.result,.feed-item{padding:8px;background:var(--card);border:1px solid var(--line);border-radius:9px;display:flex;justify-content:space-between;gap:7px;align-items:center}.result-name,.feed-main{min-width:0;font-size:10px;overflow-wrap:anywhere}.money{white-space:nowrap;text-align:right;font-size:12px}.small-money{font-size:8px;color:var(--muted)}
.feed-item{align-items:flex-start}.feed-time{width:48px;color:var(--muted);font-size:8px}.side-tag{padding:2px 5px;border-radius:5px;font-size:8px}.tag-up{color:var(--blue);background:#12293a}.tag-down{color:var(--purple);background:#241d3d}.feed-detail{font-size:8px;color:var(--muted);margin-top:2px}
.logs{height:210px;overflow:auto;margin-top:8px;padding:8px;background:#010407;border:1px solid #13202d;border-radius:11px;font-family:SFMono-Regular,Consolas,monospace;font-size:9px;font-weight:500;-webkit-overflow-scrolling:touch}.log{white-space:pre-wrap;word-break:break-word;color:#94a5b6;padding:1px 0}.log-win{color:var(--green)!important}.log-loss{color:var(--red)!important}.log-info{color:var(--blue)!important}
.empty{padding:14px;text-align:center;color:#445467;font-size:10px}.green{color:var(--green)!important}.red{color:var(--red)!important}.gold{color:var(--gold)!important}.blue{color:var(--blue)!important}
@media(max-width:1050px){.kpis{grid-template-columns:repeat(4,minmax(0,1fr))}.two-col,.markets{grid-template-columns:1fr}}
@media(max-width:620px){h1{font-size:15px}.shell{padding:8px}.topbar{padding:10px}.kpis{grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.chart{height:140px}.mid{font-size:26px}.metrics{grid-template-columns:repeat(3,1fr)}.result,.feed-item{flex-wrap:wrap}}
</style></head><body><div class="shell">
<header class="topbar"><div class="brand"><div class="brand-icon">⚡</div><div><h1>BTC Divergence Bot</h1><div class="sub">BTC >0.65 · alt same side <0.50 · one 100-share fill per pair</div></div></div><div class="pills"><span class="pill" id="connection">UI LINK</span><span class="pill warn" id="clobStatus">CLOB CONNECTING</span><span class="pill warn" id="discoveryStatus">DISCOVERY</span><span class="pill" id="rate">0/s</span><span class="pill" id="uptime">00:00</span></div></header>
<section class="kpis" id="kpis"></section>
<section class="two-col"><div class="panel"><div class="panel-head"><span>Global equity curve</span><strong id="equityValue">—</strong></div><div class="chart"><svg id="equityChart" preserveAspectRatio="none"></svg></div></div><div class="panel"><div class="panel-head"><span>Strategy & connection</span><strong>ACTIVE RULES</strong></div><div class="config-grid" id="configGrid"></div></div></section>
<section class="panel"><div class="panel-head"><span>Live binary markets · CLOB order books</span><strong id="tickInfo">WAITING</strong></div><div class="markets" id="marketsGrid"></div></section>
<section class="two-col"><div class="panel"><div class="panel-head"><span>Open positions · floating P&L</span><strong id="positionCount">0</strong></div><div class="positions" id="positionsGrid"></div></div><div class="panel"><div class="panel-head"><span>Active windows</span><strong id="windowCount">0</strong></div><div class="windows" id="windowsGrid"></div></div></section>
<section class="two-col"><div class="panel"><div class="panel-head"><span>Resolved windows</span><strong>FINAL 2S / GAMMA</strong></div><div class="results" id="resultsGrid"></div></div><div class="panel"><div class="panel-head"><span>Execution feed</span><strong>PAPER FOK</strong></div><div class="feed" id="feedGrid"></div></div></section>
<section class="panel"><div class="panel-head"><span>Server activity</span><strong id="socketStatus">READY</strong></div><div class="logs" id="logsPanel"></div></section>
</div><script src="/socket.io/socket.io.js"></script><script>
let state=null,tickData=null,logs=[],connected=false,lastRender=0,priceHistory={},lastMessages=0,lastRateAt=Date.now(),rateValue=0;
const $=id=>document.getElementById(id),socket=io({transports:['polling','websocket'],upgrade:true,reconnectionDelay:250,reconnectionDelayMax:1000,timeout:3000});
socket.on('connect',()=>{connected=true;$('connection').textContent='UI LIVE';$('connection').className='pill live'});
socket.on('disconnect',()=>{connected=false;$('connection').textContent='UI RECONNECT';$('connection').className='pill warn'});
socket.on('log',line=>{logs.push(line);if(logs.length>300)logs.shift();renderLogs()});
socket.on('tick',data=>{tickData=data;if(!state)return;if(data.messageCount!=null)updateRate(data.messageCount);requestAnimationFrame(()=>{if(tickData===data){renderLivePrices(data);renderFloating();lastRender=Date.now()}})});
socket.on('state',data=>render(data));
function refreshState(){fetch('/api/status').then(r=>r.json()).then(render).catch(()=>{$('connection').textContent='UI RETRY';$('connection').className='pill warn'})}
refreshState();setInterval(refreshState,1000);
function money(v){if(v==null||!isFinite(v))return'—';const n=Number(v),sign=n>0?'+':n<0?'-':'$';return sign+'$'+Math.abs(n).toFixed(2)}
function cash(v){return'$'+Number(v||0).toFixed(2)}function num(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function tone(v){return Number(v)>0?'green':Number(v)<0?'red':''}function price(v){return v==null?'—':Number(v).toFixed(3)}
function short(text){text=String(text||'—');return text.length>28?text.slice(0,26)+'…':text}function clock(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function rememberPrice(key,value){if(!Number.isFinite(value))return null;const now=Date.now(),list=priceHistory[key]||(priceHistory[key]=[]);list.push({t:now,p:value});while(list.length&&now-list[0].t>2500)list.shift();const old=list.find(x=>now-x.t<=1800&&x.p!==value)||list[0];return value-old.p}
function updateRate(count){const now=Date.now();if(now-lastRateAt>=500){rateValue=Math.round((count-lastMessages)*1000/(now-lastRateAt));lastMessages=count;lastRateAt=now}$('rate').textContent=rateValue+'/s'}
function render(data){state=data;if(!logs.length&&data.logs)logs=data.logs.slice();updateRate(data.messageCount||0);
$('uptime').textContent=clock(data.uptime||0);const clob=$('clobStatus');if(data.connected){clob.textContent='CLOB LIVE';clob.className='pill live'}else{clob.textContent=data.subscribedTokens?'CLOB RECONNECTING':'CLOB CONNECTING';clob.className='pill warn'}
const disc=$('discoveryStatus'),d=data.discovery||{};if(d.currentDiscovered===d.expectedMarkets&&d.nextDiscovered===d.expectedMarkets){disc.textContent='MARKETS READY';disc.className='pill live'}else{disc.textContent='MARKETS '+((d.currentDiscovered||0)+(d.nextDiscovered||0))+'/'+(d.expectedMarkets||0)*2;disc.className='pill warn'}
$('tickInfo').textContent=num(data.tickCount)+' TICKS';const openPnl=data.unrealizedPnl??(data.positions||[]).reduce((sum,p)=>sum+positionPnlFromState(p),0);
$('kpis').innerHTML=[['Equity',cash(data.markValue),'','Current marked value'],['Total P&L',money(data.totalPnl),tone(data.totalPnl),'Since launch'],['Realized P&L',money(data.realizedPnl),tone(data.realizedPnl),'Settled result'],['Open P&L',money(openPnl),tone(openPnl),'Live mark-to-market'],['Bankroll',cash(data.bankroll),'','Cash available'],['Win Rate',data.winRate==null?'—':data.winRate+'%','',data.wins+'W / '+data.losses+'L'],['Exposure',cash(data.openValue),'','Open cost value']].map(k=>'<article class="metric"><div class="label">'+k[0]+'</div><div class="value '+k[2]+'">'+k[1]+'</div><div class="small">'+k[3]+'</div></article>').join('');
$('equityValue').textContent=cash(data.markValue);renderChart(data.equityCurve||[]);renderConfig(data);buildMarkets(data.markets||[]);renderLivePrices(tickData&&tickData.markets?.length?tickData:{t:Date.now(),markets:data.markets||[]});renderWindows(data.windows||[]);renderPositions(data.positions||[]);renderResults(data.resolvedWindows||[]);renderFeed(data.trades||[]);renderLogs();}
function renderConfig(data){const c=data.config,d=data.discovery||{},rows=[['Entry','100 sh @ CLOB ask'],['Trigger','BTC > '+c.btcStrongPrice.toFixed(2)+' · ALT < '+c.targetCheapPrice.toFixed(2)],['Limit','1 fill per altcoin pair'],['Resolution','final 2s > '+c.resolutionPrice.toFixed(2)],['Subscriptions',num(data.subscribedTokens)+' CLOB tokens'],['Discovery',d.currentDiscovered+'/'+d.expectedMarkets+' now · '+d.nextDiscovered+'/'+d.expectedMarkets+' next'],['Last discovery',d.lastDiscoveryAt?new Date(d.lastDiscoveryAt).toLocaleTimeString():'waiting'],['Reconnects',num(data.reconnects)]];
if(d.errors&&d.errors.length)rows.push(['Discovery errors',short(d.errors[0])]);
$('configGrid').innerHTML=rows.map(r=>'<div class="config-item">'+r[0]+'<b>'+r[1]+'</b></div>').join('')}
function sideHtml(asset,outcome){const lower=outcome.toLowerCase();return '<div class="side-label '+lower+'-label">'+outcome+'</div><div class="mid" id="'+lower+'-mid-'+asset+'">—</div><div class="quote-row"><span class="quote">B <b id="'+lower+'-bid-'+asset+'">—</b></span><span class="quote">A <b id="'+lower+'-ask-'+asset+'">—</b></span></div><div class="quote"><span>SPRD <b id="'+lower+'-spread-'+asset+'">—</b></span><div class="delta" id="'+lower+'-delta-'+asset+'"></div></div>'}
function buildMarkets(markets){if(!markets.length){$('marketsGrid').innerHTML='<div class="empty" style="grid-column:1/-1">Discovering exact 5-minute markets…</div>';return}
$('marketsGrid').innerHTML=markets.map(m=>'<article class="market-card" id="market-'+m.asset+'"><div class="market-top"><div><div class="asset-name">'+m.asset.toUpperCase()+'</div><div class="small">'+short(m.slug)+'</div></div><div class="timer" id="timer-'+m.asset+'">'+clock(m.remaining)+'<span>T+'+m.elapsed+'s</span></div></div><div class="sides"><div class="side">'+sideHtml(m.asset,'UP')+'</div><div class="side">'+sideHtml(m.asset,'DOWN')+'</div></div><div class="signal-line"><span>BTC SIDE <b id="lead-'+m.asset+'">—</b></span><span>TARGET <b id="target-'+m.asset+'">—</b></span><span id="signal-'+m.asset+'">MONITORING</span><span id="final-'+m.asset+'"></span></div></article>').join('')}
function renderLivePrices(packet){if(!packet||!packet.markets||!state)return;for(const market of packet.markets){const card=$('market-'+market.asset);if(!card)continue;$('timer-'+market.asset).innerHTML=clock(market.remaining)+'<span>T+'+market.elapsed+'s</span>';['up','down'].forEach(side=>{const token=market[side],key=market.asset+side,delta=rememberPrice(key,token.mid);$(side+'-bid-'+market.asset).textContent=price(token.bid);$(side+'-ask-'+market.asset).textContent=price(token.ask);$(side+'-mid-'+market.asset).textContent=price(token.mid);$(side+'-spread-'+market.asset).textContent=token.spread==null?'—':token.spread.toFixed(3);const el=$(side+'-delta-'+market.asset);el.textContent=delta==null?'HOLD':(delta>=0?'▲ +':'▼ ')+delta.toFixed(3);el.className='delta '+(delta>=0?'green':'red')})}
 const btc=packet.markets.find(m=>m.asset===state.leadAsset.toLowerCase()),btcSide=!btc?'—':(btc.up.mid>=btc.down.mid?'UP':'DOWN'),btcToken=btc?(btcSide==='UP'?btc.up:btc.down):null,btcPrice=btcToken?.mid,strong=Number.isFinite(btcPrice)&&btcPrice>state.config.btcStrongPrice;
 for(const market of packet.markets){const leadEl=$('lead-'+market.asset);if(btc)leadEl.textContent=btcSide+' '+btcPrice.toFixed(3);if(market.asset===state.leadAsset.toLowerCase()){$('signal-'+market.asset).textContent=strong?('SIGNAL '+btcSide):'LEAD MARKET';$('signal-'+market.asset).className=strong?'signal-buy':'';continue}
 const target=(btcSide==='UP'?market.up:market.down),cheap=Number.isFinite(target.mid)&&target.mid<state.config.targetCheapPrice,targetEl=$('target-'+market.asset);targetEl.textContent=btcSide+' '+price(target.mid);const el=$('signal-'+market.asset);if(strong&&cheap){el.textContent='BUY '+btcSide+' NOW';el.className='signal-buy'}else if(strong){el.textContent='SIDE NOT CHEAP';el.className='signal-lead'}else{el.textContent='WAITING BTC >'+state.config.btcStrongPrice.toFixed(2);el.className=''}const fin=$('final-'+market.asset);fin.textContent=market.elapsed>=298?('FINAL '+price(market.finalUpMax ?? market.finalDownMax)):'';
 if(market.finalUpMax!=null&&market.finalDownMax!=null)fin.textContent='FINAL U/D '+price(market.finalUpMax)+'/'+price(market.finalDownMax)}}
function positionPnlFromState(p){const packet=tickData&&tickData.markets?.find(m=>m.asset===p.asset);const token=packet&&(p.outcome==='UP'?packet.up:packet.down);const mark=Number.isFinite(token?.mid)?token.mid:p.markPrice;return p.shares*mark-p.cost-p.fee}
function renderFloating(){if(state)renderPositions(state.positions||[])}
function renderWindows(windows){$('windowCount').textContent=windows.length+' ACTIVE';if(!windows.length){$('windowsGrid').innerHTML='<div class="empty">No active 5-minute windows</div>';return}$('windowsGrid').innerHTML=windows.map(w=>'<article class="window-card"><div class="pos-top"><div><div class="label">'+w.asset.toUpperCase()+' WINDOW</div><div class="small">'+short(w.slug)+'</div></div><div class="money '+tone(w.unrealized)+'">'+money(w.unrealized)+'<div class="small-money">floating</div></div></div><div class="window-shares"><div class="share-box"><div class="label up-label">UP</div><div class="share-value blue">'+num(w.upShares)+'</div><div class="small">'+cash(w.upCost)+'</div></div><div class="share-box"><div class="label down-label">DOWN</div><div class="share-value">'+num(w.downShares)+'</div><div class="small">'+cash(w.downCost)+'</div></div><div class="share-box"><div class="label">FILLS</div><div class="share-value gold">'+w.trades+'</div><div class="small">this window</div></div></div></article>').join('')}
function renderPositions(positions){$('positionCount').textContent=positions.length+' OPEN';if(!positions.length){$('positionsGrid').innerHTML='<div class="empty">No open positions</div>';return}$('positionsGrid').innerHTML=positions.map(p=>{const pnl=p.pnl??positionPnlFromState(p);return '<article class="position"><div class="pos-top"><div><div class="small">'+p.asset.toUpperCase()+' · '+p.outcome.toUpperCase()+' · AVG '+Number(p.avgPrice).toFixed(3)+'</div><div class="pos-shares">'+num(p.shares)+' SH</div></div><div class="money '+tone(pnl)+'">'+money(pnl)+'<div class="small-money">'+p.fills+' FILLS</div></div></div><div class="metrics"><div class="cell">COST<b>'+cash(p.cost)+'</b></div><div class="cell">AVG<b>'+price(p.avgPrice)+'</b></div><div class="cell">MARK<b>'+price(p.markPrice)+'</b></div><div class="cell">VALUE<b>'+cash(p.shares*p.markPrice)+'</b></div><div class="cell">FIRST T+<b>'+p.signal.elapsed+'s</b></div></div></article>'}).join('')}
function renderResults(results){if(!results.length){$('resultsGrid').innerHTML='<div class="empty">No settled windows yet</div>';return}$('resultsGrid').innerHTML=results.map(r=>'<article class="result"><div class="result-name"><b>'+r.asset.toUpperCase()+'</b> · '+r.winner+' WINNER<div class="small-money">'+new Date(r.settledAt).toLocaleTimeString()+'</div></div><div class="money '+tone(r.pnl)+'">'+money(r.pnl)+'<div class="small-money">'+cash(r.payout)+' payout / '+cash(r.upCost+r.downCost)+' cost</div></div></article>').join('')}
function renderFeed(trades){if(!trades.length){$('feedGrid').innerHTML='<div class="empty">Waiting for divergence…</div>';return}$('feedGrid').innerHTML=trades.slice(0,40).map(t=>'<article class="feed-item"><span class="feed-time">'+new Date(t.timestamp).toLocaleTimeString()+'</span><div class="feed-main"><span class="side-tag '+(t.outcome==='UP'?'tag-up':'tag-down')+'">'+t.asset.toUpperCase()+' '+t.outcome+'</span> '+num(t.shares)+' SH @ '+Number(t.price).toFixed(3)+'<div class="feed-detail">T+'+t.signal.elapsed+'s · BTC '+t.signal.btcSide+' '+Number(t.signal.btcPrice).toFixed(3)+' vs '+Number(t.signal.targetPrice).toFixed(3)+' · '+cash(t.cost)+'</div></div><div class="money green">FOK</div></article>').join('')}
function renderChart(curve){const svg=$('equityChart');if(!curve.length){svg.innerHTML='';return}const values=curve.map(x=>x.equity),low=Math.min(...values),high=Math.max(...values),range=(high-low)||1,w=700,h=160,pad=12,pts=curve.map((point,index)=>[index/Math.max(1,curve.length-1)*w,h-pad-(point.equity-low)/range*(h-pad*2)]);const path='M'+pts.map(p=>p[0].toFixed(1)+','+p[1].toFixed(1)).join(' L'),last=pts[pts.length-1]||[0,h/2],color=state.totalPnl>=0?'#15ff9c':'#ff4a68';svg.innerHTML='<defs><linearGradient id="eqfill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="'+color+'" stop-opacity=".35"/><stop offset="1" stop-color="'+color+'" stop-opacity="0"/></linearGradient></defs><path d="'+path+' L'+last[0]+','+(h-pad)+' L0,'+(h-pad)+' Z" fill="url(#eqfill)"/><path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="2.5"/><circle cx="'+last[0]+'" cy="'+last[1]+'" r="4" fill="'+color+'"/>'}
function renderLogs(){const panel=$('logsPanel'),nearBottom=panel.scrollHeight-panel.scrollTop-panel.clientHeight<50;panel.innerHTML=logs.slice(-220).map(line=>{let cls='';if(line.includes('BUY'))cls='log-info';else if(line.includes('WIN'))cls='log-win';else if(line.includes('LOSS')||line.includes('⚠️'))cls='log-loss';return'<div class="log '+cls+'">'+escape(line)+'</div>'}).join('');if(nearBottom)panel.scrollTop=panel.scrollHeight}
function escape(value){return String(value||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
setInterval(()=>{if(tickData&&state&&Date.now()-lastRender>120){renderLivePrices(tickData);renderFloating();lastRender=Date.now()}},100);
</script></body></html>`;

app.get('/', (_, request) => request.type('html').send(dashboard));
io.on('connection', socket => socket.emit('state', engine.buildState()));
setInterval(() => io.emit('state', engine.buildState()), 250);

server.listen(port, '0.0.0.0', () => {
  console.log(`BTC divergence dashboard listening on :${port}`);
  engine.init().catch(error => console.error(`Init failure: ${error.message}`));
});
