'use strict';
const express = require('express');
const { BtcBreakoutEngine } = require('./engine');

const app = express();
const port = process.env.PORT || 8080;
const engine = new BtcBreakoutEngine({
  onLog: line => console.log(line),
});

app.get('/healthz', (_, request) => request.sendStatus(200));
app.get('/api/status', (_, response) => {
  try { response.json(engine.buildState()); }
  catch (error) { response.status(500).json({ error: error.message }); }
});

const dashboard = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BTC 5m Breakout</title><style>
:root{--bg:#000;--panel:#070707;--card:#020202;--line:#222;--muted:#9d9d9d;--blue:#38d6ff;--green:#00ff9d;--red:#ff4a68;--gold:#ffd166}
*{box-sizing:border-box;margin:0;padding:0}html{-webkit-text-size-adjust:100%}
body{background:var(--bg);color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;font-weight:800;padding-bottom:18px}
.shell{width:min(1250px,100%);margin:auto;padding:10px}.panel,.metric,.side,.position,.result,.trade-item{background:var(--panel);border:1px solid var(--line);border-radius:12px}
.topbar{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:11px;border:1px solid var(--line);border-radius:13px;background:#050505}.brand-icon{width:36px;height:36px;border-radius:9px;display:grid;place-items:center;background:#111;color:var(--gold)}h1{font-size:17px}.sub{font-size:8px;color:var(--muted);margin-top:2px}.pills{display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end}.pill{font-size:8px;text-transform:uppercase;padding:5px 7px;border:1px solid var(--line);border-radius:99px;background:#0a0a0a}.live{color:var(--green);border-color:#12483a}.warn{color:var(--gold)}
.kpis{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px;margin:8px 0}.metric{padding:9px;min-width:0}.label{font-size:7px;color:var(--muted);text-transform:uppercase;letter-spacing:.6px}.value{font-size:15px;margin-top:3px;overflow-wrap:anywhere}.small{font-size:7px;color:var(--muted);margin-top:2px}
.grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:6px}.panel{padding:9px;margin-bottom:6px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:5px;font-size:8px;color:var(--muted);text-transform:uppercase}.panel-head strong{color:#fff;font-size:11px;text-transform:none}
.market-top{display:flex;justify-content:space-between;align-items:flex-start;gap:6px}.asset{font-size:22px;color:var(--gold)}.timer{color:var(--blue);font-size:19px;text-align:right}.timer small{display:block;color:var(--muted);font-size:8px}
.sides{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:8px}.side{padding:10px;text-align:center}.side-label{font-size:9px;color:var(--muted)}.up-label{color:var(--blue)}.down-label{color:#c4b5fd}.mid{font-size:35px;line-height:1;margin:4px 0;font-variant-numeric:tabular-nums}.quotes{display:flex;justify-content:center;gap:8px;font-size:9px;color:var(--muted)}.quotes b{color:#fff}.meta{display:flex;justify-content:space-between;margin-top:5px;font-size:8px;color:var(--muted)}.stale{color:var(--gold)!important}
.position-card{min-height:145px;display:flex;flex-direction:column;justify-content:space-between}.pos-main{display:flex;justify-content:space-between;gap:8px}.outcome{font-size:24px}.shares{font-size:31px;color:var(--blue)}.pnl-big{font-size:27px;text-align:right}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;margin-top:8px}.cell{background:var(--card);border:1px solid #161616;border-radius:7px;padding:6px;font-size:7px;color:var(--muted)}.cell b{display:block;color:#fff;font-size:11px;margin-top:2px}
.config-grid,.history,.feed{display:grid;gap:5px;margin-top:7px}.config-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.config-item{background:var(--card);border:1px solid #161616;border-radius:8px;padding:7px;font-size:8px;color:var(--muted)}.config-item b{display:block;color:#fff;font-size:11px;margin-top:2px}.history,.feed{grid-template-columns:1fr;max-height:260px;overflow:auto;-webkit-overflow-scrolling:touch}
.result,.trade-item{padding:8px;display:flex;justify-content:space-between;gap:6px;align-items:center}.result-name{font-size:12px}.small-money{font-size:8px;color:var(--muted)}.money{font-size:16px;text-align:right}.action-buy{color:var(--blue)}.action-sell{color:var(--gold)}
.chart{height:135px;margin-top:7px}svg{width:100%;height:100%}.logs{height:220px;overflow:auto;background:#010101;border:1px solid var(--line);border-radius:9px;padding:8px;font-family:SFMono-Regular,Consolas,monospace;font-size:9px;font-weight:700;-webkit-overflow-scrolling:touch}.log{white-space:pre-wrap;word-break:break-word;color:#aaa;margin-bottom:2px}.win{color:var(--green)!important}.loss{color:var(--red)!important}.buy{color:var(--blue)!important}.empty{padding:14px;text-align:center;color:#666;font-size:10px}
.green{color:var(--green)!important}.red{color:var(--red)!important}.gold{color:var(--gold)!important}.blue{color:var(--blue)!important}@media(max-width:900px){.kpis{grid-template-columns:repeat(4,minmax(0,1fr))}.grid{grid-template-columns:1fr}}@media(max-width:520px){.shell{padding:7px}.kpis{grid-template-columns:repeat(2,minmax(0,1fr));gap:4px}.mid{font-size:33px}.shares{font-size:28px}.pnl-big{font-size:23px}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><div class="shell">
<header class="topbar"><div style="display:flex;align-items:center;gap:7px"><div class="brand-icon">₿</div><div><h1>BTC 5-Minute Breakout</h1><div class="sub">ENTRY ≥0.89 · STOP ≤0.79 · FINAL-2S &gt;0.90 RESOLUTION · CLOB BOOKS ONLY</div></div></div><div class="pills"><span id="connection" class="pill warn">UI LINK</span><span id="clob" class="pill warn">CLOB CONNECTING</span><span id="rate" class="pill">0/s</span><span id="uptime" class="pill">00:00</span></div></header>
<section class="kpis" id="kpis"></section>
<div class="grid"><section class="panel"><div class="panel-head"><span>Live BTC order book</span><strong id="tickInfo">WAITING</strong></div><div class="market-top"><div class="asset">BTC</div><div class="timer" id="timer">--:--<small>T+0s</small></div></div><div class="sides" id="sides"></div></section>
<section class="panel"><div class="panel-head"><span>Active position</span><strong id="positionStatus">FLAT</strong></div><div id="positionPanel"></div></section></div>
<div class="grid"><section class="panel"><div class="panel-head"><span>Global equity curve</span><strong id="equityValue">—</strong></div><div class="chart"><svg id="equityChart" preserveAspectRatio="none"></svg></div></section>
<section class="panel"><div class="panel-head"><span>Rules & martingale</span><strong id="martingaleState">BASE</strong></div><div class="config-grid" id="configGrid"></div></section></div>
<section class="panel"><div class="panel-head"><span>Window results</span><strong id="resultCount">0</strong></div><div class="history" id="resultsGrid"></div></section>
<section class="panel"><div class="panel-head"><span>Execution feed</span><strong>PAPER FOK</strong></div><div class="feed" id="feedGrid"></div></section>
<section class="panel"><div class="panel-head"><span>Server activity</span><strong id="serverStatus">READY</strong></div><div class="logs" id="logsPanel"></div></section>
</div><script>
let state=null,logs=[],lastRender=0,priceHistory={},quoteSeen={},quoteStamps={},rendered=false,lastPollCount=0,lastRateAt=Date.now(),rateValue=0;
const $=id=>document.getElementById(id),safe=fn=>{try{fn()}catch(e){console.error(e)}};
async function refreshState(){try{$('connection').textContent='UI LIVE';$('connection').className='pill live';const response=await fetch('/api/status');render(await response.json())}catch(error){$('connection').textContent='UI RETRY';$('connection').className='pill warn'}}refreshState();setInterval(refreshState,250);
function num(v){return Number(v||0).toLocaleString()}function cash(v){return'$'+Number(v||0).toFixed(2)}function money(v){if(v==null||!isFinite(v))return'—';const n=Number(v);return(n>0?'+$':n<0?'-$':'$')+Math.abs(n).toFixed(2)}function tone(v){return Number(v)>0?'green':Number(v)<0?'red':''}function price(v){return v==null?'—':Number(v).toFixed(3)}function clock(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function esc(v){return String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function updateRate(count){const now=Date.now();if(now-lastRateAt>=1000){rateValue=Math.max(0,Math.round((count-lastPollCount)*1000/(now-lastRateAt)));lastPollCount=count;lastRateAt=now}$('rate').textContent=rateValue+'/s'}
function remember(key,value){if(!Number.isFinite(value))return null;const now=Date.now(),list=priceHistory[key]||(priceHistory[key]=[]);list.push({t:now,p:value});while(list.length&&now-list[0].t>2500)list.shift();const old=list.find(item=>now-item.t<=1800&&item.p!==value)||list[0];return value-old.p}
function sideHtml(outcome,label,cls){const lower=outcome.toLowerCase();return'<div class="side"><div class="side-label '+cls+'">'+label+'</div><div class="mid" id="'+lower+'Mid">—</div><div class="quotes"><span>B <b id="'+lower+'Bid">—</b></span><span>A <b id="'+lower+'Ask">—</b></span></div><div class="meta"><span>SPRD <span id="'+lower+'Spread">—</span></span><span id="'+lower+'Age">WAIT</span></div><div class="meta"><span>Δ <span id="'+lower+'Delta">HOLD</span></span><span id="'+lower+'Final"></span></div></div>'}
function render(data){const changed=state&&state.windowStart!==data.windowStart;if(changed){priceHistory={};quoteSeen={};quoteStamps={};rendered=false}state=data;$('uptime').textContent=clock(data.uptime);$('clob').textContent=data.connected?'CLOB LIVE':'POLL RETRY';$('clob').className='pill '+(data.connected?'live':'warn');$('serverStatus').textContent=data.connected?'LIVE':'RETRYING';updateRate(data.pollCount||0);
$('kpis').innerHTML=[['Equity',cash(data.markValue),'',cash(data.bankroll)+' cash'],['Total P&L',money(data.totalPnl),tone(data.totalPnl),'Since launch'],['Realized',money(data.realizedPnl),tone(data.realizedPnl),cash(data.totalFees)+' fees'],['Floating',money(data.unrealizedPnl),tone(data.unrealizedPnl),'live mark'],['Current Size',num(data.currentShares)+' SH','',data.lossStreak+' loss streak'],['Next Loss Size',num(data.nextShares)+' SH','','×'+data.martingaleMultiplier.toFixed(1)],['Win Rate',data.winRate==null?'—':data.winRate+'%','',data.wins+'W / '+data.losses+'L']].map(k=>'<article class="metric"><div class="label">'+k[0]+'</div><div class="value '+k[2]+'">'+k[1]+'</div><div class="small">'+k[3]+'</div></article>').join('');
$('martingaleState').textContent=data.lossStreak?('M'+data.lossStreak):'BASE';const rows=[['Entry','mid ≥ '+data.config.entryPrice.toFixed(2)+' · ask fill'],['Stop','bid ≤ '+data.config.stopPrice.toFixed(2)],['Resolution','final 2s mid > '+data.config.resolutionPrice.toFixed(2)],['Base',num(data.config.baseShares)+' SH'],['Martingale','×'+data.config.martingaleMultiplier.toFixed(1)+' · max M'+data.config.maxMartingales],['Sequence',(data.stakeSequence||[]).map(num).join(' → ')+' → RESET'],['CLOB','batch /books every '+data.config.pollMs+'ms'],['Window start',new Date(data.windowStart*1000).toLocaleTimeString()]];$('configGrid').innerHTML=rows.map(row=>'<div class="config-item">'+row[0]+'<b>'+row[1]+'</b></div>').join('');
if(!rendered){$('sides').innerHTML=sideHtml('UP','UP','up-label')+sideHtml('DOWN','DOWN','down-label');rendered=true}const packet={t:data.serverTime,windowStart:data.windowStart,markets:data.markets};renderMarket(packet,'CLOB BOOK');renderPosition(data.position,data.unrealizedPnl);renderChart(data.equityCurve||[]);renderResults(data.results||[]);renderFeed(data.trades||[]);renderLogs()}
function renderMarket(packet,label){if(!packet?.markets?.length)return;const market=packet.markets[0];$('tickInfo').textContent=label+' · '+new Date(packet.t).toLocaleTimeString();$('timer').innerHTML=clock(market.remaining)+'<small>T+'+market.elapsed+'s</small>';for(const side of ['up','down']){const token=market[side],key=side,stamp=Number(token.updatedAt)||0;if(stamp&&quoteStamps[key]!==stamp){quoteStamps[key]=stamp;quoteSeen[key]=Date.now()}else if(stamp&&!quoteSeen[key])quoteSeen[key]=Date.now();const seen=quoteSeen[key],stale=!seen||Date.now()-seen>=4000,delta=remember(key,token.mid);$(side+'Bid').textContent=price(token.bid);$(side+'Ask').textContent=price(token.ask);$(side+'Mid').textContent=price(token.mid);$(side+'Spread').textContent=token.spread==null?'—':token.spread.toFixed(3);const age=$(side+'Age');age.textContent=!stamp?'NO BOOK':!seen?'WAIT':Date.now()-seen<1000?'NOW':((Date.now()-seen)/1000).toFixed(1)+'s';age.className=stale?'stale':'';const el=$(side+'Delta');el.textContent=!quoteSeen[key]?'WAIT':delta==null?'HOLD':(delta>=0?'▲ +':'▼ ')+delta.toFixed(3);el.className=delta==null?'':delta>=0?'green':'red';$(side+'Final').textContent=market.finalUpMax!=null&&market.finalDownMax!=null?('FINAL '+price(market.finalUpMax)+'/'+price(market.finalDownMax)):''}}
function renderPosition(position,floating){if(!position){$('positionStatus').textContent='FLAT';$('positionPanel').innerHTML='<div class="empty">No open BTC position<br>Waiting for UP or DOWN ≥0.89</div>';return}$('positionStatus').textContent=position.outcome.toUpperCase()+' OPEN';const pnl=floating??position.pnl;$('positionPanel').innerHTML='<div class="position-card"><div class="pos-main"><div><div class="outcome">'+position.outcome+'</div><div class="shares">'+num(position.shares)+' SH</div></div><div class="pnl-big '+tone(pnl)+'">'+money(pnl)+'<div class="small-money">floating</div></div></div><div class="metrics"><div class="cell">ENTRY<b>'+price(position.avgPrice)+'</b></div><div class="cell">COST<b>'+cash(position.cost)+'</b></div><div class="cell">MARK<b>'+price(position.markPrice)+'</b></div><div class="cell">M-LEVEL<b>M'+position.martingaleLevel+'</b></div></div><div class="small" style="margin-top:6px">Opened T+'+(position.signal?.elapsed||0)+'s at trigger '+price(position.signal?.triggerPrice)+' · stop closes on bid ≤0.79</div></div>'}
function renderResults(results){$('resultCount').textContent=results.length+' SETTLED';if(!results.length){$('resultsGrid').innerHTML='<div class="empty">No completed windows yet</div>';return}$('resultsGrid').innerHTML=results.map(r=>'<article class="result"><div><div class="result-name">'+new Date(r.settledAt).toLocaleTimeString()+' · '+(r.result||'UNKNOWN')+'<div class="small-money">'+num(r.buyCount)+' buy / '+num(r.sellCount)+' sell · winner '+(r.winner||'—')+'</div></div></div><div class="money '+tone(r.realizedPnl)+'">'+money(r.realizedPnl)+'<div class="small-money">cost '+cash(r.invested)+' · next '+(r.nextShares==null?'—':num(r.nextShares))+' SH</div></div></article>').join('')}
function renderFeed(trades){if(!trades.length){$('feedGrid').innerHTML='<div class="empty">Waiting for first breakout…</div>';return}$('feedGrid').innerHTML=trades.slice(0,60).map(t=>'<article class="trade-item"><div><span class="'+(t.action==='BUY'?'action-buy':'action-sell')+'">'+t.action+' BTC '+t.outcome+'</span> '+num(t.shares)+' SH @ '+price(t.price)+'<div class="small-money">'+new Date(t.timestamp).toLocaleTimeString()+' · '+esc(t.reason)+' · M'+t.martingaleLevel+'</div></div><div class="money '+(t.action==='SELL'?tone(t.pnl):'')+'">'+(t.action==='BUY'?cash(t.cost):money(t.pnl))+'<div class="small-money">'+t.orderType+'</div></div></article>').join('')}
function renderChart(curve){const svg=$('equityChart');if(!curve.length){svg.innerHTML='';return}const values=curve.map(point=>point.equity),low=Math.min(...values),high=Math.max(...values),range=(high-low)||1,width=700,height=120,pad=8,points=curve.map((point,index)=>[index/Math.max(1,curve.length-1)*width,height-pad-(point.equity-low)/range*(height-pad*2)]),path='M'+points.map(point=>point[0].toFixed(1)+','+point[1].toFixed(1)).join(' L'),last=points.at(-1),color=state.totalPnl>=0?'#00ff9d':'#ff4a68';$('equityValue').textContent=cash(state.markValue);svg.innerHTML='<path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="2.5"/><circle cx="'+last[0]+'" cy="'+last[1]+'" r="4" fill="'+color+'"/>'}
function renderLogs(){const panel=$('logsPanel'),nearBottom=panel.scrollHeight-panel.scrollTop-panel.clientHeight<50;panel.innerHTML=logs.slice(-240).map(line=>{let cls='';if(line.includes('BUY'))cls='buy';else if(line.includes('WIN'))cls='win';else if(line.includes('LOSS')||line.includes('STOP')||line.includes('⚠️'))cls='loss';return'<div class="log '+cls+'">'+esc(line)+'</div>'}).join('');if(nearBottom)panel.scrollTop=panel.scrollHeight}
</script></body></html>`;
app.get('/', (_, request) => request.type('html').send(dashboard));
app.listen(port, '0.0.0.0', () => {
  console.log(`BTC breakout dashboard listening on :${port}`);
  engine.init().catch(error => console.error(`Init failure: ${error.message}`));
});
